### ISSUE TITLE
QC plots missing

### ISSUE THREAD

**Issue by alxndrkalinin** [jump-cellpainting/cpg0016-jump-orf-data#6]
@niranjchandrasekaran I found out that for most plates there are 3 QC visualizations:
* _cell_count.png
* _correlation.png
* _position_effect.png

However, some plates are missing some of three ([example](https://github.com/jump-cellpainting/jump-orf-data/tree/master/quality_control/heatmap/2021_04_26_Batch1/BR00121540)). Do you have an idea why that can be so?

**Comment by niranjchandrasekaran** [comment]
Alex and I discussed offline. These are likely `untreated` plates. If there are ORF plates that are also missing these files, then  I will look into this further.

**Comment by alxndrkalinin** [comment]
Turns out, my issues with visualizing plate effects were in part due to a bug (fixed in broadinstitute/position-effect-correction#6) and in part due to the fact that `Batch1` [has 2](https://github.com/jump-cellpainting/jump-orf-data/blob/7e133aba021e4adf1dbbf99169956d503c9aa833/config_files/config_control.yml#LL55C25-L55C25) `untreated` plates that [differ in presence/absence of polybrene](https://github.com/jump-cellpainting/morphmap/blob/main/0.explore-data/output/experiment-metadata.tsv#L24). 

So all good now!
